# End of grade 1 / start of grade 2 — word|syllables (oral blending)
EN_GR1 = """
about|a-bout
after|af-ter
again|a-gain
animal|an-i-mal
around|a-round
away|a-way
basket|bas-ket
because|be-cause
before|be-fore
birthday|birth-day
blanket|blan-ket
breakfast|break-fast
brother|broth-er
bunny|bun-ny
cannot|can-not
carry|car-ry
chicken|chick-en
children|chil-dren
chocolate|choc-o-late
cookie|cook-ie
could|could
cousin|cou-sin
dolphin|dol-phin
dragon|dra-gon
during|dur-ing
eight|eight
enjoy|en-joy
evening|eve-ning
every|ev-ery
family|fam-i-ly
father|fa-ther
finger|fin-ger
flower|flow-er
follow|fol-low
garden|gar-den
ginger|gin-ger
happy|hap-py
helpful|help-ful
hockey|hoc-key
honey|hon-ey
hungry|hun-gry
inside|in-side
jacket|jack-et
kitten|kit-ten
kitchen|kit-chen
ladder|lad-der
lemon|lem-on
letter|let-ter
little|lit-tle
marker|mark-er
market|mar-ket
maybe|may-be
monkey|mon-key
morning|mor-ning
mother|moth-er
moving|mov-ing
music|mu-sic
myself|my-self
napkin|nap-kin
neighbor|neigh-bor
nothing|noth-ing
number|num-ber
ocean|o-cean
often|of-ten
orange|or-ange
other|oth-er
outside|out-side
pancake|pan-cake
paper|pa-per
parent|par-ent
party|par-ty
peanut|pea-nut
people|peo-ple
picture|pic-ture
pillow|pil-low
pirate|pi-rate
pizza|piz-za
pocket|pock-et
police|po-lice
pretty|pret-ty
princess|prin-cess
puppet|pup-pet
purple|pur-ple
puzzle|puz-zle
rabbit|rab-bit
river|riv-er
robot|ro-bot
rocket|rock-et
sailor|sail-or
second|sec-ond
shadow|shad-ow
sister|sis-ter
sleepy|sleep-y
snowman|snow-man
soccer|soc-cer
spider|spi-der
squirrel|squir-rel
station|sta-tion
strawberry|straw-ber-ry
student|stu-dent
summer|sum-mer
Sunday|Sun-day
sunset|sun-set
swing|swing
teacher|teach-er
think|think
ticket|tick-et
tiger|ti-ger
today|to-day
together|to-geth-er
tomato|to-ma-to
travel|trav-el
treehouse|tree-house
triangle|tri-an-gle
tricycle|tri-cy-cle
turkey|tur-key
turtle|tur-tle
twelve|twelve
umbrella|um-brel-la
uncle|un-cle
under|un-der
until|un-til
velvet|vel-vet
violin|vi-o-lin
visit|vis-it
wagon|wag-on
weather|weath-er
window|win-dow
winter|win-ter
wonder|won-der
yellow|yel-low
yourself|your-self
zebra|ze-bra
""".strip().splitlines()

FR_GR1 = """
animal|a-ni-mal
anniversaire|an-ni-ver-saire
apporter|ap-por-ter
arbre|ar-bre
arriver|ar-ri-ver
attendre|at-ten-dre
automne|au-tomne
avion|a-vion
avril|a-vril
baleine|ba-leine
banane|ba-nane
bateau|ba-teau
biberon|bi-be-ron
biscuit|bis-cuit
bouteille|bou-teille
cadeau|ca-deau
cahier|ca-hier
camarade|ca-ma-rade
camion|ca-mion
camping|cam-ping
caramel|ca-ra-mel
carotte|ca-rot-te
cerise|ce-rise
chambre|cham-bre
chanter|chan-ter
chanson|chan-son
chapeau|cha-peau
chocolat|cho-co-lat
classe|classe
collage|col-lage
couleur|cou-leur
courrier|cour-rier
cousin|cou-sin
crayon|cray-on
danseur|dan-seur
décembre|dé-cem-bre
demain|de-main
descendre|des-cen-dre
dessin|des-sin
dimanche|di-man-che
dîner|di-ner
douzaine|dou-zaine
échelle|é-chel-le
école|é-cole
écouter|é-cou-ter
éléphant|é-lé-phant
enfant|en-fant
entrer|en-trer
escalier|es-ca-lier
étoile|é-toile
été|é-té
février|fé-vrier
fille|fi-lle
forêt|fo-rêt
fourmi|four-mi
fromage|fro-mage
fête|fête
galette|ga-lette
garage|ga-rage
garderie|gar-de-rie
garçon|gar-çon
gâteau|gâ-teau
gentil|gen-til
grenouille|gre-nouille
hibou|hi-bou
histoire|his-toire
hiver|hi-ver
hockey|hoc-key
idée|i-dée
inviter|in-vi-ter
janvier|jan-vier
jardin|jar-din
jeudi|jeu-di
journal|jour-nal
journée|jour-née
juillet|jui-llet
juin|juin
lundi|lun-di
mardi|mar-di
mercredi|mer-cre-di
magasin|ma-ga-sin
manger|man-ger
manteau|man-teau
marmotte|mar-motte
matin|ma-tin
mitaine|mi-tai-ne
monnaie|mon-nai-e
montagne|mon-tagne
montre|mon-tre
musique|mu-sique
neige|nei-ge
noël|no-ël
nuage|nu-age
octobre|oc-tobre
oiseau|oi-seau
oreille|o-reille
oublier|ou-bli-er
ouvrir|ou-vrir
pantalon|pan-ta-lon
papillon|pa-pil-lon
parents|pa-rents
parapluie|pa-ra-pluie
parler|par-ler
peigne|peigne
piano|pi-a-no
piscine|pis-cine
plage|plage
pluie|plu-ie
poisson|pois-son
pomme|pom-me
porte|por-te
pourquoi|pour-quoi
printemps|prin-temps
pyjama|py-ja-ma
quatre|qua-tre
question|ques-tion
quitter|quit-ter
regarder|re-gar-der
renard|re-nard
rentrer|rent-rer
répondre|ré-pon-dre
restaurant|res-tau-rant
rivière|ri-vière
robot|ro-bot
samedi|sa-me-di
sandwich|sand-wich
sauter|sau-ter
septembre|sep-tem-bre
serrer|ser-rer
soeur|soeur
soleil|so-leil
sortir|sor-tir
soulier|sou-lier
souris|sou-ris
stylo|sty-lo
tante|tante
tapis|ta-pis
théâtre|thé-â-tre
tortue|tor-tue
train|train
trésor|tré-sor
trois|trois
tuque|tuque
uniforme|u-ni-for-me
vendredi|ven-dre-di
vent|vent
village|vil-lage
vingt|vingt
violet|vi-o-let
visite|vi-site
voisin|voi-sin
voiture|voi-ture
voyage|vo-yage
zéro|zé-ro
""".strip().splitlines()
